-- ============================================
-- FASHIONSTORE - ESQUEMA DE BASE DE DATOS LIMPIO (FINAL)
-- Fecha: 2026-01-19
-- Descripción: Script consolidado sin seeds. Define el estado final de la BD.
-- ============================================

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- 2. TABLAS PRINCIPALES (Estructura Final)
-- ============================================

-- 2.1 Categorías
CREATE TABLE categories (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  size_type TEXT DEFAULT 'clothing' CHECK (size_type IN ('clothing', 'footwear', 'universal')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON COLUMN categories.size_type IS 'Tipo de talla: clothing (XXS-XXL), footwear (36-46), universal (Única)';

-- 2.2 Productos
CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
  offer_price NUMERIC(10, 2) CHECK (offer_price IS NULL OR offer_price >= 0),
  category_id UUID REFERENCES categories(id) ON DELETE SET NULL,
  active BOOLEAN DEFAULT TRUE,
  is_offer BOOLEAN DEFAULT FALSE,
  deleted_at TIMESTAMPTZ DEFAULT NULL, -- Soft Delete
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.3 Variantes
CREATE TABLE product_variants (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  product_id UUID REFERENCES products(id) ON DELETE CASCADE,
  size TEXT NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
  UNIQUE(product_id, size)
);

-- 2.4 Imágenes
CREATE TABLE product_images (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  product_id UUID REFERENCES products(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  "order" INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.5 Pedidos
CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_number BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE, -- Identificador visible #1001
  -- Cliente
  customer_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Enlace a usuario registrado (opcional)
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT,
  -- Envío
  shipping_address TEXT NOT NULL,
  shipping_city TEXT NOT NULL,
  shipping_postal_code TEXT NOT NULL,
  shipping_country TEXT DEFAULT 'España',
  -- Pago
  total_amount NUMERIC(10, 2) NOT NULL,
  status TEXT DEFAULT 'pending', -- El check constraint se maneja mejor en app o flexible para devoluciones
  stripe_session_id TEXT UNIQUE,
  -- Devoluciones y Tracking
  refunded_amount NUMERIC(10, 2) DEFAULT 0,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.6 Items de Pedido
CREATE TABLE order_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id) ON DELETE SET NULL,
  variant_id UUID REFERENCES product_variants(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  price_at_purchase NUMERIC(10, 2) NOT NULL
);

-- 2.7 Envíos (Shipments)
CREATE TABLE order_shipments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  carrier TEXT NOT NULL,
  tracking_number TEXT,
  tracking_url TEXT,
  shipped_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(order_id)
);

-- 2.8 Perfiles de Clientes
CREATE TABLE customer_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  phone TEXT,
  default_address TEXT,
  default_city TEXT,
  default_postal_code TEXT,
  default_country TEXT DEFAULT 'España',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.9 Configuración
CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  value_bool BOOLEAN,
  value_number NUMERIC(10, 2),
  description TEXT
);

-- ============================================
-- 3. MÓDULOS ESPECÍFICOS
-- ============================================

-- 3.1 Cupones
CREATE TABLE coupons (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code TEXT UNIQUE NOT NULL,
  stripe_coupon_id TEXT NOT NULL,
  discount_type TEXT NOT NULL CHECK (discount_type IN ('fixed', 'percentage')),
  discount_value NUMERIC(10, 2) NOT NULL CHECK (discount_value > 0),
  min_purchase_amount NUMERIC(10, 2) DEFAULT 0,
  max_discount_amount NUMERIC(10, 2),
  start_date TIMESTAMPTZ DEFAULT NOW(),
  end_date TIMESTAMPTZ,
  max_uses INTEGER,
  current_uses INTEGER DEFAULT 0,
  max_uses_per_customer INTEGER DEFAULT 1,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE coupon_usages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  coupon_id UUID REFERENCES coupons(id) ON DELETE CASCADE,
  customer_email TEXT NOT NULL,
  order_id UUID REFERENCES orders(id) ON DELETE SET NULL,
  used_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(coupon_id, customer_email, order_id)
);

-- 3.2 Promociones (CMS)
CREATE TABLE promotions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT NOT NULL,
  mobile_image_url TEXT,
  cta_text TEXT,
  cta_link TEXT,
  coupon_id UUID REFERENCES coupons(id) ON DELETE SET NULL,
  locations JSONB NOT NULL DEFAULT '["home_hero"]',
  priority INTEGER DEFAULT 10,
  style_config JSONB DEFAULT '{}',
  start_date TIMESTAMPTZ DEFAULT NOW(),
  end_date TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE promotion_history (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  promotion_id UUID REFERENCES promotions(id) ON DELETE CASCADE, -- Note: references nullable if parent deleted logic used
  changed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  changes JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE promotion_drafts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  promotion_data JSONB NOT NULL DEFAULT '{}',
  wizard_step INTEGER DEFAULT 1,
  last_saved TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX idx_promotion_drafts_user_id ON promotion_drafts(user_id);

-- 3.3 Devoluciones
CREATE TABLE returns (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'requested',
  refund_amount NUMERIC(10, 2) DEFAULT 0,
  refund_method TEXT DEFAULT 'original_payment',
  customer_notes TEXT,
  admin_notes TEXT,
  rejection_reason TEXT,
  tracking_number TEXT,
  return_label_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  approved_at TIMESTAMPTZ,
  received_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ
);

CREATE TABLE return_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  return_id UUID NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
  order_item_id UUID REFERENCES order_items(id) ON DELETE SET NULL,
  product_variant_id UUID REFERENCES product_variants(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  reason TEXT NOT NULL,
  reason_details TEXT,
  inspection_status TEXT DEFAULT 'pending',
  inspection_notes TEXT,
  restock_approved BOOLEAN DEFAULT FALSE,
  refund_amount NUMERIC(10, 2) DEFAULT 0
);

CREATE TABLE return_images (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  return_id UUID NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
  return_item_id UUID REFERENCES return_items(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  uploaded_by TEXT DEFAULT 'customer',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.4 Newsletter
CREATE TABLE newsletter_subscribers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email TEXT UNIQUE NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  unsubscribe_token UUID DEFAULT uuid_generate_v4() UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE newsletter_campaigns (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  subject TEXT NOT NULL,
  content TEXT NOT NULL,
  status TEXT DEFAULT 'draft',
  sent_count INTEGER DEFAULT 0,
  total_recipients INTEGER DEFAULT 0,
  failed_count INTEGER DEFAULT 0,
  last_error TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  sent_at TIMESTAMPTZ
);

CREATE TABLE newsletter_send_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  campaign_id UUID REFERENCES newsletter_campaigns(id) ON DELETE CASCADE,
  subscriber_id UUID REFERENCES newsletter_subscribers(id) ON DELETE SET NULL,
  subscriber_email TEXT NOT NULL,
  status TEXT,
  error_message TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE newsletter_rate_limits (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ip_address TEXT NOT NULL,
  attempts INTEGER DEFAULT 1,
  first_attempt_at TIMESTAMPTZ DEFAULT NOW(),
  last_attempt_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.5 Facturas
CREATE SEQUENCE IF NOT EXISTS invoice_number_seq START 1;
CREATE TABLE invoices (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id UUID UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
  invoice_number TEXT UNIQUE NOT NULL,
  issued_at TIMESTAMPTZ DEFAULT NOW(),
  pdf_url TEXT,
  customer_nif TEXT NOT NULL,
  customer_fiscal_name TEXT NOT NULL,
  customer_fiscal_address TEXT NOT NULL,
  subtotal NUMERIC(10,2) NOT NULL,
  tax_rate NUMERIC(5,2) NOT NULL DEFAULT 21.00,
  tax_amount NUMERIC(10,2) NOT NULL,
  total NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- 4. ÍNDICES
-- ============================================
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_active ON products(active);
CREATE INDEX idx_products_deleted_at ON products(deleted_at);
CREATE INDEX idx_products_active_deleted ON products(active, deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_email ON orders(customer_email);
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_order_number ON orders(order_number);
CREATE INDEX idx_coupons_code ON coupons(code);
CREATE INDEX idx_promotions_active ON promotions(is_active);
CREATE INDEX idx_returns_order ON returns(order_id);
CREATE INDEX idx_returns_user ON returns(user_id);

-- ============================================
-- 5. RLS (Row Level Security)
-- ============================================
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE returns ENABLE ROW LEVEL SECURITY;
-- (Habilitar para el resto de tablas también)

-- Políticas Simplificadas (Ejemplos Críticos)

-- Productos: Públicos activos
CREATE POLICY "Public read active products" ON products FOR SELECT TO anon, authenticated USING (active = true AND deleted_at IS NULL);
CREATE POLICY "Admin full access products" ON products FOR ALL TO authenticated USING ((auth.jwt() -> 'user_metadata' ->> 'is_admin')::boolean = true);

-- Pedidos: Clientes ven los suyos
CREATE POLICY "Customer view own orders" ON orders FOR SELECT TO authenticated USING (customer_id = auth.uid());
CREATE POLICY "Public view order by session" ON orders FOR SELECT TO anon, authenticated USING (stripe_session_id IS NOT NULL);
CREATE POLICY "Admin manage orders" ON orders FOR ALL TO authenticated USING ((auth.jwt() -> 'user_metadata' ->> 'is_admin')::boolean = true);

-- ============================================
-- 6. STORAGE
-- ============================================
INSERT INTO storage.buckets (id, name, public) VALUES 
('product-images', 'product-images', true),
('documents', 'documents', true)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- 7. FUNCIONES RPC (Versiones Finales)
-- ============================================

-- Function: create_checkout_order (Returns JSON with order_number)
CREATE OR REPLACE FUNCTION create_checkout_order(
  p_customer_name TEXT,
  p_customer_email TEXT,
  p_customer_phone TEXT,
  p_shipping_address TEXT,
  p_shipping_city TEXT,
  p_shipping_postal_code TEXT,
  p_shipping_country TEXT,
  p_total_amount NUMERIC,
  p_stripe_session_id TEXT,
  p_items JSONB,
  p_customer_id UUID DEFAULT NULL
) RETURNS JSON AS $$
DECLARE
  v_order_id UUID;
  v_order_number BIGINT;
  v_item JSONB;
BEGIN
  INSERT INTO orders (
    customer_name, customer_email, customer_phone,
    shipping_address, shipping_city, shipping_postal_code, shipping_country,
    total_amount, status, stripe_session_id, customer_id
  ) VALUES (
    p_customer_name, p_customer_email, p_customer_phone,
    p_shipping_address, p_shipping_city, p_shipping_postal_code, p_shipping_country,
    p_total_amount, 'pending', p_stripe_session_id, p_customer_id
  ) RETURNING id, order_number INTO v_order_id, v_order_number;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    INSERT INTO order_items (order_id, product_id, variant_id, quantity, price_at_purchase)
    VALUES (
      v_order_id,
      (v_item->>'product_id')::UUID,
      (v_item->>'variant_id')::UUID,
      (v_item->>'quantity')::INTEGER,
      (v_item->>'price_at_purchase')::NUMERIC
    );
  END LOOP;

  RETURN json_build_object(
    'order_id', v_order_id,
    'order_number', v_order_number
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
GRANT EXECUTE ON FUNCTION create_checkout_order TO anon, authenticated;


-- Function: get_customer_orders (Includes order_number)
CREATE OR REPLACE FUNCTION get_customer_orders(
  p_customer_id UUID
) RETURNS TABLE (
  id UUID,
  order_number BIGINT, -- AÑADIDO
  customer_name TEXT,
  customer_email TEXT,
  total_amount NUMERIC,
  status TEXT,
  created_at TIMESTAMPTZ,
  item_count BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    o.id, 
    o.order_number,
    o.customer_name, 
    o.customer_email,
    o.total_amount, 
    o.status, 
    o.created_at,
    (SELECT COUNT(*) FROM order_items oi WHERE oi.order_id = o.id) as item_count
  FROM orders o
  WHERE o.customer_id = p_customer_id
  ORDER BY o.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Function: get_order_by_session (Includes order_number)
CREATE OR REPLACE FUNCTION get_order_by_session(
  p_stripe_session_id TEXT
) RETURNS TABLE (
  id UUID,
  order_number BIGINT, -- AÑADIDO
  customer_name TEXT,
  customer_email TEXT,
  customer_phone TEXT,
  shipping_address TEXT,
  shipping_city TEXT,
  shipping_postal_code TEXT,
  shipping_country TEXT,
  total_amount NUMERIC,
  status TEXT,
  stripe_session_id TEXT,
  created_at TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    o.id, 
    o.order_number,
    o.customer_name, o.customer_email, o.customer_phone,
    o.shipping_address, o.shipping_city, o.shipping_postal_code, o.shipping_country,
    o.total_amount, o.status, o.stripe_session_id, o.created_at
  FROM orders o
  WHERE o.stripe_session_id = p_stripe_session_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Function: reserve_stock
CREATE OR REPLACE FUNCTION reserve_stock(p_variant_id UUID, p_quantity INTEGER) 
RETURNS BOOLEAN AS $$
DECLARE v_rows INTEGER;
BEGIN
  UPDATE product_variants SET stock = stock - p_quantity WHERE id = p_variant_id AND stock >= p_quantity;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  RETURN v_rows > 0;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function: restore_stock
CREATE OR REPLACE FUNCTION restore_stock(p_variant_id UUID, p_quantity INTEGER) 
RETURNS BOOLEAN AS $$
DECLARE v_rows INTEGER;
BEGIN
  UPDATE product_variants SET stock = stock + p_quantity WHERE id = p_variant_id;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  RETURN v_rows > 0;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 8. CONFIGURACIÓN INICIAL (Solo claves críticas, sin datos de ejemplo)
INSERT INTO settings (key, value, value_bool, value_number, description) VALUES
('maintenance_mode', NULL, false, NULL, 'Modo mantenimiento'),
('offers_enabled', NULL, false, NULL, 'Ofertas flash activas'),
('shipping_cost', NULL, NULL, 4.99, 'Coste envío estándar'),
('free_shipping_threshold', NULL, NULL, 50.00, 'Umbral envío gratis'),
('tax_rate', NULL, NULL, 21.00, 'IVA por defecto')
ON CONFLICT (key) DO NOTHING;

-- 9. TRIGGERS BÁSICOS
-- Trigger perfil usuario
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.customer_profiles (id, full_name)
  VALUES (NEW.id, NEW.raw_user_meta_data->>'full_name');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Trigger update_updated_at (Genérico)
CREATE OR REPLACE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_promotions_updated_at BEFORE UPDATE ON promotions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_coupons_updated_at BEFORE UPDATE ON coupons FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

