-- ============================================
-- FASHIONSTORE - MIGRACIÓN 026
-- Sistema de Numeración Secuencial de Pedidos
-- Fecha: 2026-01-15
-- Autor: Sistema
-- ============================================
-- 
-- OBJETIVO:
-- Añadir columna order_number (BIGINT) a la tabla orders
-- para reemplazar el uso de UUID como identificador visible
-- Formato display: #A000001 (6 dígitos con padding)
--
-- CAMBIOS:
-- 1. Nueva columna: orders.order_number (BIGINT, NOT NULL, UNIQUE)
-- 2. Índice para búsquedas rápidas
-- 3. Migración de datos históricos (asignar números secuenciales)
-- 4. Secuencia sincronizada con el máximo valor actual
--
-- TIEMPO ESTIMADO: 5-10 minutos (depende del número de pedidos)
-- IMPACTO: Bloqueo temporal de escrituras en tabla orders
-- ============================================

BEGIN;

-- ============================================
-- PASO 1: Crear columna con IDENTITY
-- ============================================
-- IDENTITY es similar a SERIAL pero más estándar SQL
-- GENERATED BY DEFAULT permite insertar valores manualmente si es necesario
ALTER TABLE orders
ADD COLUMN order_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

DO $$ BEGIN
  RAISE NOTICE 'Paso 1/6: Columna order_number creada';
END $$;

-- ============================================
-- PASO 2: Crear índice
-- ============================================
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON orders(order_number);

DO $$ BEGIN
  RAISE NOTICE 'Paso 2/6: Índice idx_orders_order_number creado';
END $$;

-- ============================================
-- PASO 3: Migrar datos históricos
-- ============================================
-- Asigna números secuenciales a pedidos existentes
-- ordenados por fecha de creación (los más antiguos primero)
DO $$
DECLARE
  affected_rows INT;
BEGIN
  WITH sorted_orders AS (
    SELECT 
      id, 
      ROW_NUMBER() OVER (ORDER BY created_at ASC) as rn
    FROM orders
    WHERE order_number IS NULL
  )
  UPDATE orders
  SET order_number = sorted_orders.rn
  FROM sorted_orders
  WHERE orders.id = sorted_orders.id;
  
  GET DIAGNOSTICS affected_rows = ROW_COUNT;
  RAISE NOTICE 'Paso 3/6: % pedidos históricos actualizados con números secuenciales', affected_rows;
END $$;

-- ============================================
-- PASO 4: Sincronizar secuencia
-- ============================================
-- Ajusta la secuencia para que el próximo número sea mayor que el máximo actual
-- Esto evita duplicados cuando se creen nuevos pedidos
DO $$
DECLARE
  next_val BIGINT;
BEGIN
  SELECT setval('orders_order_number_seq', (SELECT COALESCE(MAX(order_number), 0) FROM orders)) INTO next_val;
  RAISE NOTICE 'Paso 4/6: Secuencia sincronizada. Próximo valor: %', next_val + 1;
END $$;

-- ============================================
-- PASO 5: Hacer columna obligatoria (NOT NULL)
-- ============================================
-- Ahora que todos los pedidos tienen un número, hacemos la columna obligatoria
ALTER TABLE orders 
ALTER COLUMN order_number SET NOT NULL;

DO $$ BEGIN
  RAISE NOTICE 'Paso 5/6: Columna order_number configurada como NOT NULL';
END $$;

-- ============================================
-- PASO 6: Añadir constraint de unicidad
-- ============================================
-- Crítico: Asegura que no haya números de pedido duplicados
ALTER TABLE orders 
ADD CONSTRAINT orders_order_number_unique UNIQUE (order_number);

DO $$ BEGIN
  RAISE NOTICE 'Paso 6/6: Constraint de unicidad añadido';
END $$;

COMMIT;

-- ============================================
-- VERIFICACIÓN POST-MIGRACIÓN
-- ============================================
DO $$
DECLARE
  total_orders INT;
  orders_with_number INT;
  max_number INT;
  next_value BIGINT;
  has_nulls INT;
  has_duplicates INT;
BEGIN
  -- Contar pedidos
  SELECT COUNT(*) INTO total_orders FROM orders;
  SELECT COUNT(*) INTO orders_with_number FROM orders WHERE order_number IS NOT NULL;
  SELECT MAX(order_number) INTO max_number FROM orders;
  SELECT last_value INTO next_value FROM orders_order_number_seq;
  
  -- Verificar nulls
  SELECT COUNT(*) INTO has_nulls FROM orders WHERE order_number IS NULL;
  
  -- Verificar duplicados
  SELECT COUNT(*) INTO has_duplicates FROM (
    SELECT order_number 
    FROM orders 
    GROUP BY order_number 
    HAVING COUNT(*) > 1
  ) duplicates;
  
  RAISE NOTICE '';
  RAISE NOTICE '═══════════════════════════════════════════════════════';
  RAISE NOTICE '           VERIFICACIÓN DE MIGRACIÓN 026              ';
  RAISE NOTICE '═══════════════════════════════════════════════════════';
  RAISE NOTICE 'Total de pedidos en BD:        %', total_orders;
  RAISE NOTICE 'Pedidos con order_number:      %', orders_with_number;
  RAISE NOTICE 'Máximo order_number asignado:  %', max_number;
  RAISE NOTICE 'Próximo número disponible:     %', next_value + 1;
  RAISE NOTICE '';
  RAISE NOTICE 'Verificaciones:';
  RAISE NOTICE '  - Pedidos con NULL:          % (debe ser 0)', has_nulls;
  RAISE NOTICE '  - Números duplicados:        % (debe ser 0)', has_duplicates;
  RAISE NOTICE '';
  
  -- Validar que todo está correcto
  IF has_nulls > 0 THEN
    RAISE WARNING '⚠️  ATENCIÓN: Hay % pedidos sin order_number', has_nulls;
  END IF;
  
  IF has_duplicates > 0 THEN
    RAISE WARNING '⚠️  ATENCIÓN: Hay % números de pedido duplicados', has_duplicates;
  END IF;
  
  IF total_orders = orders_with_number AND has_nulls = 0 AND has_duplicates = 0 THEN
    RAISE NOTICE '✅ MIGRACIÓN COMPLETADA EXITOSAMENTE';
  ELSE
    RAISE WARNING '⚠️  VERIFICAR RESULTADOS - Posibles problemas detectados';
  END IF;
  
  RAISE NOTICE '═══════════════════════════════════════════════════════';
  RAISE NOTICE '';
  
END $$;

-- ============================================
-- QUERY DE MUESTRA
-- ============================================
-- Mostrar los últimos 5 pedidos con sus números
DO $$
DECLARE
  sample_row RECORD;
BEGIN
  RAISE NOTICE 'Muestra de pedidos (últimos 5):';
  RAISE NOTICE '';
  
  FOR sample_row IN 
    SELECT 
      order_number,
      substring(id::text, 1, 8) as short_id,
      customer_email,
      created_at
    FROM orders
    ORDER BY created_at DESC
    LIMIT 5
  LOOP
    RAISE NOTICE 'Order #% | UUID: % | Cliente: % | Fecha: %',
      sample_row.order_number,
      sample_row.short_id,
      sample_row.customer_email,
      sample_row.created_at;
  END LOOP;
  
  RAISE NOTICE '';
END $$;

-- ============================================
-- FIN DE MIGRACIÓN 026
-- ============================================
-- 
-- PRÓXIMOS PASOS:
-- 1. Actualizar función RPC create_checkout_order para retornar order_number
-- 2. Actualizar código frontend/backend para usar formatOrderId()
-- 3. Probar creación de nuevos pedidos
-- 4. Verificar emails y facturas con nuevo formato
--
-- En caso de problemas, ejecutar: rollback_026.sql
-- ============================================
